# Generated by Django 5.0.4 on 2025-04-17 11:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_promocode_max_uses_per_user_promocodeusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocodeusage',
            unique_together={('user', 'promo_code')},
        ),
    ]
