# Generated by Django 5.0.4 on 2025-04-16 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_rating_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='updated_at',
        ),
    ]
