# Generated by Django 5.0.4 on 2025-04-28 03:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_status_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='next_status_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
