# Generated by Django 5.0.4 on 2025-04-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_promocodeusage_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
