# Generated by Django 5.1.7 on 2025-04-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_paymentmethod_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
