# Generated by Django 5.0.4 on 2025-04-18 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_promo_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocodeusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
        migrations.AlterUniqueTogether(
            name='promocodeusage',
            unique_together={('user', 'promo_code', 'order')},
        ),
    ]
