# Generated by Django 5.2 on 2025-04-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_discount_order_shipping_price'),
        ('store', '0008_alter_promocodeusage_unique_together_and_more'),
    ]

    operations = [
    ]
