# Generated by Django 5.1.7 on 2025-04-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_passwordreset_user_alter_cartitem_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
