# Generated by Django 5.1.7 on 2025-04-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
