# Generated by Django 5.1.7 on 2025-04-07 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_shippingaddress_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
