# Generated by Django 5.1.7 on 2025-04-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
